name: Earth Tours
favicon: null
layout_spectrum: 0.99466
typography_spectrum: 0.50082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13241e'
    - '#619530'
    - '#426f2a'
    - '#73b72c'
    - '#dcebcc'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.6110817466396838
purpose: []
