name: Earth Tours
favicon: null
layout_spectrum: 0.10109160514548421
typography_spectrum: 0.3110680643003434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13125176494941115
  lightness: 0.2506959300953895
  saturation: 0.8336655586026609
  rhythmicContrast: 0.6110817466396838
purpose: []
